# Generated by Django 6.0.4 on 2026-04-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0001_initial'),
    ]

    operations = [
    ]
